import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import GlobalState from "@/context";
import { ThemeProvider } from "next-themes";
import { SpeedInsights } from "@vercel/speed-insights/next"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "21SZN APP",
  description: "Generated by create next app",
  
  
};

export default function RootLayout({ children }) {

  // const { theme, setTheme } = useTheme();
  return (
    <html lang="en">
      <head>
      </head>
      <meta name="theme-color" media="(prefers-color-scheme: light)" content="#00bcd4" />
      <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#121212" />
      <body className={`${inter.className} bg-backgroundLight dark:bg-backgroundDark `}>
      <ThemeProvider defaultTheme="light" attribute="class">
        <GlobalState>
          <Navbar />
          <main className="bg-backgroundLight dark:bg-backgroundDark text-textLight dark:text-textDark flex min-h-screen flex-col mt-[79px]">
            {children}
          </main>
        </GlobalState>
        </ThemeProvider>
      </body>
    </html>
  );
}

////////////////////////////////////////////////////////////////
////////////////////////////////
// Changes made to the ThemeProvider class
////////////////////////////////
////////////////////////////////////////////////////////////////